import { createRoot } from 'react-dom/client';
import JourneyGame from './components/game/journey';
import './app/globals.css';
import './app/flow.css';
import './app/atmosphere.css';
import './app/bracelet.css';
import './app/motion.css';
import './app/relay.css';
import './app/path-sky.css';
import './app/path-journey.css';
import './app/date-motion.css';
import './app/journey-continuity.css';
import './app/sapphire-discovery.css';
import './app/path-closure.css';
import './app/immersive.css';
import './app/opening-lesson.css';
import './app/path-destinations.css';
import './app/date-nebula.css';
import './app/date-nebula-scene.css';
import './app/stone-entry.css';

createRoot(document.getElementById('root')!).render(<JourneyGame />);
