'use client';
import { useEffect, useReducer, useRef, useState, type CSSProperties } from 'react';
import { flushSync } from 'react-dom';
import { ArrowUpRight, ArrowRight, ArrowLeft, VolumeX, Volume2, Sparkles, Check, RotateCcw, HelpCircle, X, Play, Minus, Circle, Radio, Gem, PackageCheck, Aperture } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { gift } from '@/lib/gift-config';
import { CHAPTERS, WORDS, MORSE, LETTERS, initialState, transition, restore, canContinue, signalTimings, type GameState, type Action } from '@/lib/game';

const STORAGE='w25-signal-v1';
const HINTS=[[],['任选四个词。没有正确答案，选你想带去未来的就好。'],['移动滑块，观察光环与信号强度。','目标频率在 60–75 之间。','把频率调到 68，再点击“留下这束光”。'],['按编号依次触碰星点。亮起的下一颗星会等待你。','圆点是短暂的光，横线是停留更久的光。','一共三组：第一组 3 颗，第二、三组各 5 颗。'],['转动光线，在三个明亮的刻度附近停下，再收集记忆。','三个刻度在 24、52、80 附近。','也可以点击下方的“寻找下一道光”，帮你对齐。'],['先播放一遍，再用短光与长光卡片还原节奏。','点 = 短光；划 = 三倍长度的长光。每一组对应一个字符。','三组分别是 · — — / · · — — — / · · · · ·，对应 W、2、5。'],['依次安放四种线索。每一步都会把结构图补全。'],['最后一段路要在屏幕之外完成。','开始交付后，暂时放下手机，留意身边的人。','亲手收到礼物后，再回来确认。页面不会自动判断实物。']];
const POSITIONS=[[18,22],[47,13],[78,28],[12,51],[32,43],[55,51],[76,45],[87,62],[18,77],[35,86],[53,74],[71,86],[87,80]];
const DURATIONS=['','1–2 MIN','2 MIN','2–3 MIN','2 MIN','3–4 MIN','2–3 MIN','1–2 MIN'];
const TITLES=['','愿它们，与你同往。','有一种光，会留下。','星星也有，自己的语言。','一小块，属于你的时间。','听见回声里的名字。','原来，你早已见过它。','剩下的距离，在屏幕之外。'];
const DESCS=['','如果只能带上四样东西，走向下一段旅程，你会选择什么？','在不同的频率间慢慢寻找，直到那束光变得清晰。','沿着编号触碰星星。看一看，哪些是一瞬，哪些是停留。','转动光线，让藏在石头里的三段记忆慢慢浮现。','把听见的短与长，放进同一封信里。不需要预先懂任何密码。','颜色、星辰、石头与回声。你只是还没见过，它们在一起的样子。','信号已经抵达。现在，让它拥有真实的重量。'];

type ModelContext={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
function useSound(enabled:boolean){
 const ctx=useRef<AudioContext|null>(null);const nodes=useRef<OscillatorNode[]>([]);
 function stop(){nodes.current.forEach(n=>{try{n.stop();}catch{}});nodes.current=[];}
 function play(pattern:string){
  stop();if(!enabled)return;
  try{const Constructor=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!Constructor)return;
   const c=ctx.current??new Constructor();ctx.current=c;void c.resume();let time=c.currentTime+.06;
   signalTimings(pattern).forEach((ms,i)=>{if(i%2===0){const o=c.createOscillator(),gain=c.createGain();o.type='sine';o.frequency.value=523.25;gain.gain.setValueAtTime(0,time);gain.gain.linearRampToValueAtTime(.09,time+.02);gain.gain.setValueAtTime(.09,time+ms/1000-.03);gain.gain.linearRampToValueAtTime(0,time+ms/1000);o.connect(gain);gain.connect(c.destination);o.start(time);o.stop(time+ms/1000+.02);nodes.current.push(o);}time+=ms/1000;});
  }catch{/* Visual rhythm is always available. */}
 }
 useEffect(()=>{if(!enabled)stop();},[enabled]);
 useEffect(()=>{const hidden=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',hidden);return()=>{stop();void ctx.current?.close();document.removeEventListener('visibilitychange',hidden);};},[]);
 return {play,stop};
}
function SignalOrbit({active=false}:{active?:boolean}){return <div className={`signal-orbit ${active?'active':''}`} aria-hidden="true"><div className="orbit-ring r1"/><div className="orbit-ring r2"/><div className="orbit-ring r3"/><div className="signal-core">✦</div><span className="orbit-label">{active?'SIGNAL ACQUIRED':'UNKNOWN ORIGIN'}</span></div>}
function Pattern({pattern}:{pattern:string}){return <span className="pattern" aria-label={pattern.replaceAll('.','短光 ').replaceAll('-','长光 ')}>{[...pattern].map((c,i)=><i key={i} className={c==='.'?'dot':'dash'}/>)}</span>}
function Bracelet({stage,rotation=0}:{stage:number;rotation?:number}){
 const symbols=MORSE.join(' ').split('');
 return <svg className="bracelet" viewBox="0 0 420 330" role="img" aria-label="W25 手链结构示意图：三组短珠和长珠分别表示 W、2、5，搭配蓝宝石。并非实际模型。"><defs><radialGradient id="bead"><stop stopColor="#f5f6ed"/><stop offset=".45" stopColor={stage>=1?gift.favoriteColor:'#7c889c'}/><stop offset="1" stopColor="#414760"/></radialGradient></defs><g transform={`rotate(${rotation},210,160)`}><ellipse cx="210" cy="158" rx="135" ry="102" fill="none" stroke="#b7c6da" strokeOpacity=".25" strokeDasharray={stage<4?'3 8':undefined}/>{symbols.map((v,i)=>{const a=(i/symbols.length)*Math.PI*2-Math.PI/2;const x=210+135*Math.cos(a),y=158+102*Math.sin(a);if(v===' ')return null;return <g key={i} opacity={stage>=4?1:.13} transform={`translate(${x},${y}) rotate(${a*180/Math.PI+90})`}>{v==='.'?<circle r="9" fill="url(#bead)"/>:<rect x="-18" y="-6" width="36" height="12" rx="6" fill="url(#bead)"/>}</g>})}<path d="M 210 248 l 16 22 -16 24 -16 -24 z" fill={gift.stoneColor} stroke="#accdff" opacity={stage>=3?1:.08}/>{stage>=2&&[[-64,-28],[54,-19],[-35,34]].map(([x,y],i)=><text key={i} x={210+x} y={158+y} fill="#d2deed" fontSize="16" textAnchor="middle">✧</text>)}</g><text x="210" y="158" fill="#d9e7c1" textAnchor="middle" fontFamily="monospace" fontSize="22" letterSpacing="8">{stage===4?'W25':'···'}</text><text x="210" y="320" fill="#8f9fb5" textAnchor="middle" fontFamily="monospace" fontSize="10" letterSpacing="2">DESIGN SCHEMATIC · 01</text></svg>
}
export default function Home(){
 const [state,dispatch]=useReducer(transition,initialState);const [hydrated,setHydrated]=useState(false);const [saved,setSaved]=useState(true);const [sound,setSound]=useState(false);
 const [help,setHelp]=useState(false),[resetOpen,setResetOpen]=useState(false),[journal,setJournal]=useState(false);
 const [tune,setTune]=useState(18),[angle,setAngle]=useState(0),[rotation,setRotation]=useState(0),[draft,setDraft]=useState(''),[feedback,setFeedback]=useState('');
 const [playing,setPlaying]=useState(false),[pulse,setPulse]=useState(false),[elapsed,setElapsed]=useState(0),[confirmReceived,setConfirmReceived]=useState(false);
 const [modelStatus,setModelStatus]=useState<'none'|'loading'|'ready'|'error'>('none');const [arSupported,setArSupported]=useState(false);
 const timerRefs=useRef<ReturnType<typeof setTimeout>[]>([]), headingRef=useRef<HTMLHeadingElement>(null);const stateRef=useRef(state);stateRef.current=state;
 const audio=useSound(sound);
 const apply=(a:Action)=>dispatch(a);
 const chapter=state.chapter;const hintCount=state.hints[chapter];
 const stopPlayback=()=>{timerRefs.current.forEach(clearTimeout);timerRefs.current=[];setPlaying(false);setPulse(false);audio.stop();};
 function playSignal(pattern:string){stopPlayback();setPlaying(true);audio.play(pattern);let offset=0;signalTimings(pattern).forEach((duration,i)=>{timerRefs.current.push(setTimeout(()=>setPulse(i%2===0),offset));offset+=duration;});timerRefs.current.push(setTimeout(()=>{setPlaying(false);setPulse(false);},offset));}
 useEffect(()=>{try{dispatch({type:'restore',state:restore(localStorage.getItem(STORAGE))});}catch{setSaved(false);}setHydrated(true);const a=document.createElement('a');try{setArSupported(a.relList.supports('ar'));}catch{}},[]);
 useEffect(()=>{if(!hydrated)return;try{localStorage.setItem(STORAGE,JSON.stringify(state));}catch{setSaved(false);}},[state,hydrated]);
 useEffect(()=>{stopPlayback();setDraft('');setFeedback('');setConfirmReceived(false);if(chapter===2&&state.colorDone)setTune(gift.tuningTarget);if(hydrated){window.scrollTo({top:0,behavior:'instant'});headingRef.current?.focus();}},[chapter]);
 useEffect(()=>{const stop=()=>{if(document.hidden)stopPlayback();};document.addEventListener('visibilitychange',stop);return()=>{timerRefs.current.forEach(clearTimeout);document.removeEventListener('visibilitychange',stop);};},[]);
 useEffect(()=>{if(state.delivery!=='waiting'||chapter!==7)return;const tick=()=>{const remaining=Math.max(0,Math.ceil((state.deadline-Date.now())/1000));setElapsed(remaining);if(remaining===0)dispatch({type:'delivery-ready'});};tick();const id=setInterval(tick,500);return()=>clearInterval(id);},[state.delivery,state.deadline,chapter]);
 useEffect(()=>{if(chapter!==6||!gift.usdzUrl)return;const ctrl=new AbortController();setModelStatus('loading');fetch(gift.usdzUrl,{method:'HEAD',signal:ctrl.signal}).then(r=>setModelStatus(r.ok&&r.headers.get('content-type')?.includes('model/vnd.usdz')?'ready':'error')).catch(()=>{if(!ctrl.signal.aborted)setModelStatus('error');});return()=>ctrl.abort();},[chapter]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const schema={type:'object',properties:{},additionalProperties:false};const validate=(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');};
  const register=(name:string,title:string,description:string,readOnlyHint:boolean,fn:()=>unknown)=>{try{void Promise.resolve(context.registerTool({name,title,description,inputSchema:schema,annotations:{readOnlyHint},execute(input){validate(input);return fn();}},{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register('read_journey','读取旅程进度','读取当前章节和已收集的线索，不揭示未解锁章节。',true,()=>({chapter:stateRef.current.chapter,title:CHAPTERS[stateRef.current.chapter-1]??'开场',canContinue:canContinue(stateRef.current),delivery:stateRef.current.delivery}));
  register('reveal_hint','显示下一条提示','为当前章节显示渐进提示，不跳关、不完成现实交付。',false,()=>{if(stateRef.current.chapter===0)throw Error('Begin the journey first');flushSync(()=>{dispatch({type:'hint'});setHelp(true);});return {chapter:stateRef.current.chapter,hint:HINTS[stateRef.current.chapter][Math.min(stateRef.current.hints[stateRef.current.chapter]-1,HINTS[stateRef.current.chapter].length-1)]};});
  return()=>lifecycle.abort();
 },[]);
 const strength=Math.max(0,100-Math.abs(tune-gift.tuningTarget)*2);const aligned=Math.abs(tune-gift.tuningTarget)<=5;
 const facetTargets=[24,52,80];const currentFacet=facetTargets.findIndex(t=>Math.abs(t-angle)<=5);
 const next=()=>apply({type:'next'});
 const replayGroup=Math.min(state.decoded,2);
 const submitCode=()=>{if(draft===MORSE[state.decoded]){apply({type:'decode',pattern:draft});setDraft('');setFeedback('回声已接通。这个字符被保存了。');}else{setFeedback('这一组还没有对上。试着再听一次，留意长光停留的时间。');}};
 return <div className="universe" style={{'--favorite':gift.favoriteColor,'--stone':gift.stoneColor} as CSSProperties}>
  <div className="grain"/>
  <header className="topbar"><button className="brand brand-button" aria-label="返回开场，保留进度" onClick={()=>apply({type:'visit',chapter:0})}>✳ <span>星间来信<small>A SIGNAL BETWEEN STARS</small></span></button><div className="header-actions"><button className="quiet" onClick={()=>setSound(v=>!v)} aria-pressed={sound} aria-label={sound?'关闭声音':'开启声音'}>{sound?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{sound?'声音开启':'声音关闭'}</span></button>{chapter>0&&<button className="icon-button" onClick={()=>setJournal(true)} aria-label="打开已收集的线索"><Aperture size={19}/></button>}</div></header>
  {chapter===0?<><main className="intro"><div className="eyebrow"><span className="live-dot"/> INCOMING TRANSMISSION · 001</div><SignalOrbit/><p className="overline">有一束信号，正在寻找某个人。</p><h1 ref={headingRef} tabIndex={-1}>穿过星海，<br/>此刻抵达。</h1><p className="intro-copy">它带着一些微光、一些未说出口的话。<br/>你愿意听听看吗？</p><button disabled={!hydrated} className="primary" onClick={()=>state.unlocked>0?apply({type:'visit',chapter:state.unlocked}):next()}>{!hydrated?'正在接通信号…':state.unlocked>0?'继续这段旅程':'接收信号'}<ArrowUpRight size={20}/></button><p className="micro"><Sparkles size={13}/> 七段旅程 · 慢慢探索约 15–20 分钟</p>{state.unlocked>0&&<button className="text-button" onClick={()=>setResetOpen(true)}>重新接收</button>}</main><footer className="intro-footer"><span>每一次相遇，都有自己的频率。</span><span>EST. ∞ LIGHT YEARS</span></footer></>:
  <div className="journey-layout"><aside className="journey-rail"><p className="rail-heading">THE JOURNEY</p><nav aria-label="章节进度">{CHAPTERS.map((title,i)=><button key={title} aria-current={chapter===i+1?'step':undefined} className={`chapter-link ${chapter===i+1?'current':''} ${i+1<state.unlocked?'done':''}`} disabled={i+1>state.unlocked} onClick={()=>apply({type:'visit',chapter:i+1})}><span className="chapter-number">{i+1<state.unlocked?<Check size={12}/>:String(i+1).padStart(2,'0')}</span><span>{i+1<=state.unlocked?title:'尚未抵达'}</span></button>)}</nav><div className="rail-bottom"><span className="live-dot"/>{saved?'进度保存在这台设备':'当前浏览器未能保存进度'}</div></aside>
  <main className="chapter-main"><div className="chapter-topline"><span>CHAPTER {String(chapter).padStart(2,'0')} / 07</span><span>{DURATIONS[chapter]}</span></div><div className="mobile-steps" aria-label={`第 ${chapter} 章，共 7 章`}>{CHAPTERS.map((_,i)=><span key={i} className={i+1<=chapter?'lit':''}/>)}</div><section className="chapter-content" key={chapter}>
  {state.delivery==='complete'&&chapter===7?<><div className="complete-emblem"><PackageCheck size={44} strokeWidth={1}/></div><p className="eyebrow success">PHYSICAL OBJECT FOUND</p><h1 className="ending-title" ref={headingRef} tabIndex={-1}>原来，收件人是你。</h1><p className="delivery-complete">DELIVERY COMPLETE</p><p className="ending-english">Some things shouldn’t stay virtual.</p><div className="blessings-final">{state.wishes.map(n=><p key={n}><span>{WORDS[n][0]}</span>{WORDS[n][2]}</p>)}</div><p className="personal-message">{gift.finalMessage}</p><p className="birthday">{gift.recipient&&`${gift.recipient}，`}生日快乐。</p><p className="micro">{gift.birthday} · W25</p><button className="secondary" onClick={()=>setJournal(true)}>把这一路，重新看一遍 <Aperture size={17}/></button></>:
  <><div className="chapter-heading"><p className="overline">{CHAPTERS[chapter-1]}</p><h2 ref={headingRef} tabIndex={-1}>{TITLES[chapter]}</h2><p className="description">{DESCS[chapter]}</p></div>
  {chapter===1&&<><div className="wish-grid">{WORDS.map(([zh,en],i)=><label key={en} className={`wish-card ${state.wishes.includes(i)?'selected':''}`}><span className="wish-index">0{i+1}</span><span className="wish-label">{zh}<small>{en}</small></span><Checkbox aria-label={`选择${zh}`} checked={state.wishes.includes(i)} disabled={!state.wishes.includes(i)&&state.wishes.length===4} onCheckedChange={()=>apply({type:'wishes',values:state.wishes.includes(i)?state.wishes.filter(n=>n!==i):[...state.wishes,i]})}/></label>)}</div><p className="selection-count"><span>{state.wishes.length} / 4</span> 个愿望，准备随行</p>{state.wishes.length>0&&<div className="reflection"><span>给未来的一句话</span><p>{WORDS[state.wishes[state.wishes.length-1]][2]}</p></div>}</>}
  {chapter===2&&<><div className={`tuning-visual ${aligned?'aligned':''}`} style={{'--strength':strength/100} as CSSProperties}><div className="frequency-rings"><div/><div/><div/></div><div className="frequency-light"/><span className="frequency-label">{state.colorDone?'COLOR HELD':aligned?'SIGNAL ALIGNED':'SEARCHING FREQUENCY'}</span></div><div className="tuner"><div className="control-label"><label id="tune-label">光的频率</label><span>{String(tune).padStart(2,'0')} <small>/ 100</small></span></div><Slider aria-labelledby="tune-label" value={[tune]} onValueChange={v=>setTune(Array.isArray(v)?v[0]:v)} min={0} max={100} step={1}/><div className="slider-marks"><span>微弱</span><span>清晰度 {Math.round(strength)}%</span><span>遥远</span></div></div>{!state.colorDone?<button className="secondary" disabled={!aligned} onClick={()=>apply({type:'color'})}>留下这束光 <Sparkles size={17}/></button>:<div className="discovery"><span className="color-chip" style={{background:gift.favoriteColor}}/><div><small>FRAGMENT 01 · COLOR</small><h3>{gift.favoriteColorName}</h3><p>{gift.favoriteColorConfirmed?'原来，你喜欢的颜色，也能成为一束被收藏的光。':'此处使用示例配色。正式交付时，这束光会换成你喜欢的颜色。'}</p></div></div>}</>}
  {chapter===3&&<><div className="star-map"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{POSITIONS.slice(0,Math.max(0,state.stars-1)).map(([x,y],i)=><line key={i} x1={x} y1={y} x2={POSITIONS[i+1][0]} y2={POSITIONS[i+1][1]} stroke={i===2||i===7?'#738397':'#becde1'} strokeOpacity=".45" strokeWidth=".2" strokeDasharray={i===2||i===7?'1 2':undefined}/>)}</svg>{POSITIONS.map(([x,y],i)=><button key={i} className={`map-star ${i<state.stars?'collected':''} ${i===state.stars?'next-star':''}`} style={{left:`${x}%`,top:`${y}%`}} disabled={i>state.stars} onClick={()=>{if(i===state.stars)apply({type:'star',index:i});else playSignal(MORSE.join('')[i]);}} aria-label={`第 ${i+1} 颗星，${MORSE.join('')[i]==='.'?'短光':'长光'}${i<state.stars?'，已收集':''}`}><span>{i<state.stars?(MORSE.join('')[i]==='.'?'•':'—'):'✦'}</span><small>{String(i+1).padStart(2,'0')}</small></button>)}<span className="map-coordinate">FIELD 025 · UNKNOWN CONSTELLATION</span></div><p className="selection-count"><span>{state.stars} / 13</span> 个光的痕迹</p><div className="signal-fragments">{MORSE.map((pattern,i)=><div key={i}><small>0{i+1}</small><Pattern pattern={pattern.slice(0,Math.max(0,state.stars-[0,3,8][i]))}/></div>)}</div>{state.stars===13&&<div className="reflection"><span>你发现了两种痕迹</span><p>星星是点。停留久一点，就留下了轨迹。<br/>短与长，或许能说些什么。</p></div>}</>}
  {chapter===4&&<><div className={`stone-reader ${currentFacet>=0?'resonant':''}`}><div className="stone-scan" style={{transform:`rotate(${angle*3.6}deg)`}}/><Gem size={85} strokeWidth={.65}/><span>{state.facets.length===3?gift.stoneEnglish:'UNKNOWN MINERAL'}</span></div><div className="tuner"><div className="control-label"><label id="angle-label">让光线绕过石头</label><span>{angle}°</span></div><Slider aria-labelledby="angle-label" value={[angle]} onValueChange={v=>setAngle(Array.isArray(v)?v[0]:v)} min={0} max={100}/><div className="slider-marks"><span>0</span><span>24 · 52 · 80</span><span>100</span></div></div><button className="secondary" disabled={currentFacet<0||state.facets.includes(currentFacet)} onClick={()=>apply({type:'facet',index:currentFacet})}>{currentFacet>=0&&state.facets.includes(currentFacet)?'这段记忆已收集':'收集光中的记忆'}<Gem size={17}/></button><button className="text-button" disabled={state.facets.length===3} onClick={()=>setAngle(facetTargets.find((_,i)=>!state.facets.includes(i))??0)}>寻找下一道光</button><div className="memory-list">{[gift.birthday,gift.birthstone,'你来到这个世界，值得被记住。'].map((text,i)=><div key={i} className={state.facets.includes(i)?'found':''}><span>{state.facets.includes(i)?<Check size={14}/>:String(i+1).padStart(2,'0')}</span><p>{state.facets.includes(i)?text:'等待光线经过'}</p></div>)}</div>{state.facets.length===3&&<p className="chapter-note">在这份礼物里，蓝宝石承载着对你诞生的纪念。<br/>A small piece of the year you arrived.</p>}</>}
  {chapter===5&&<><div className="decoded-slots">{LETTERS.map((letter,i)=><div className={i<state.decoded?'solved':i===state.decoded?'decoding':''} key={letter}><span>{i<state.decoded?letter:'?'}</span><small>0{i+1}</small></div>)}</div>{state.decoded<3?<><div className="decoder-player"><div className={`pulse-light ${pulse?'on':''}`} aria-hidden="true"/><div><p>第 {state.decoded+1} 组回声</p><small>{playing?'留意光停留的时间…':'可以反复聆听，也可以看下面的短与长。'}</small></div><button className="icon-button" aria-label={playing?'停止播放':'播放当前回声'} onClick={()=>playing?stopPlayback():playSignal(MORSE[replayGroup])}>{playing?<X size={19}/>:<Play size={19}/>}</button></div><details className="visual-code"><summary>用眼睛读这段回声</summary><Pattern pattern={MORSE[replayGroup]}/><p>把这组短光与长光，依次放进下方。</p></details><div className="draft-slots" aria-live="polite" aria-label={`已放入 ${draft.length} 个信号`}>{draft?<Pattern pattern={draft}/>:<span>把回声放在这里</span>}</div><div className="signal-cards"><button disabled={draft.length>=5} onClick={()=>{setDraft(draft+'.');setFeedback('');}}><Circle size={16} fill="currentColor"/><strong>短光</strong><small>PULSE · 1 拍</small></button><button disabled={draft.length>=5} onClick={()=>{setDraft(draft+'-');setFeedback('');}}><Minus size={28}/><strong>长光</strong><small>ECHO · 3 拍</small></button></div><div className="decoder-actions"><button className="text-button" disabled={!draft} onClick={()=>setDraft(draft.slice(0,-1))}><RotateCcw size={14}/> 撤回一张</button><button className="secondary" disabled={!draft} onClick={submitCode}>接通回声 <ArrowRight size={17}/></button></div><p className="feedback" role="status">{feedback}</p></>:<div className="revelation"><p className="eyebrow">SIGNAL DECODED</p><h3>W25，原来是它的形状。</h3><p>这种由短与长组成的语言，叫摩尔斯电码。</p><div className="morse-key">{MORSE.map((p,i)=><div key={p}><Pattern pattern={p}/><span>= {LETTERS[i]}</span></div>)}</div><p>点与线将成为短珠与长珠。<br/>这段信号，会被做成可以戴在手上的东西。</p></div>}</>}
  {chapter===6&&<><Bracelet stage={state.assembled} rotation={rotation}/><div className="assembly-steps">{['留下颜色','点亮星空','嵌入蓝宝石','排列 W25'].map((label,i)=><div key={label} className={i<state.assembled?'assembled':''}><span>{i<state.assembled?<Check size={14}/>:`0${i+1}`}</span>{label}</div>)}</div>{state.assembled<4?<button className="secondary" onClick={()=>apply({type:'assemble'})}>{['让颜色靠近','让星空落下','安放蓝宝石','把回声串在一起'][state.assembled]}<Sparkles size={17}/></button>:<><div className="tuner rotation-tuner"><label id="rotation-label">转动结构，读一读那些短与长</label><Slider aria-labelledby="rotation-label" value={[rotation]} min={-180} max={180} onValueChange={v=>setRotation(Array.isArray(v)?v[0]:v)}/></div><div className="model-slot"><span className="eyebrow">VIRTUAL OBJECT ASSEMBLED</span>{modelStatus==='ready'?<><p>真实模型已接通。让它暂时来到你的身边。</p>{arSupported?<a className="ar-link secondary" rel="ar" href={gift.usdzUrl}><img src="model-poster.svg" alt="在身边查看手链 AR 模型"/><span>在身边查看 ↗</span></a>:<><p>请在 iPhone / iPad 的 Safari 打开以使用 AR。</p><a className="text-button" href={gift.usdzUrl}>下载 USDZ 模型</a></>}</>:<p>{modelStatus==='loading'?'正在接通模型…':modelStatus==='error'?'模型暂时无法打开，先带着这份结构图继续。':'目前展示设计结构示意，真实手链模型等待接入。'}<br/>你仍然可以完成下一段旅程。</p>}</div></>}</>}
  {chapter===7&&<div className={`delivery-scene ${state.delivery==='waiting'?'waiting':''}`}><div className="delivery-ring"><PackageCheck size={42} strokeWidth={1}/></div><p className="eyebrow">{state.delivery==='idle'?'SIGNAL SYNCHRONIZED':state.delivery==='waiting'?'DELIVERY IN PROGRESS':'AWAITING YOUR CONFIRMATION'}</p><div className="delivery-status"><span>虚拟信物</span><span className="success">已成形</span><span>现实信物</span><span>{state.delivery==='ready'?'等待你确认':'等待抵达'}</span></div>{state.delivery==='idle'?<><p>把手机轻轻放下，看看身边的人。<br/>有些话，要交到你手里才算说完。</p><button className="primary" onClick={()=>{apply({type:'delivery-start',deadline:Date.now()+gift.deliveryWaitSeconds*1000});playSignal(MORSE.join(' '));}}>开始最后的投递 <ArrowRight size={19}/></button><p className="micro">轻放手机即可，不需要翻面或开启相机。</p></>:state.delivery==='waiting'?<><h3>让星光，经过掌心。</h3><p>此刻请暂时离开屏幕。<br/>这束信号最后的路，由身边的人走完。</p><p className="countdown" aria-live="off">{elapsed} <small>秒</small></p></>:<><h3>它来到你手里了吗？</h3><p>慢慢来，信号会一直等你。</p><label className="receive-check"><Checkbox checked={confirmReceived} onCheckedChange={v=>setConfirmReceived(!!v)} aria-label="我已亲手收到现实中的礼物"/><span>我已亲手收到现实中的礼物</span></label><button className="primary" disabled={!confirmReceived} onClick={()=>apply({type:'receive'})}>确认收到 <Check size={18}/></button></>}</div>}
  {chapter<7&&<div className="chapter-footer"><button className="help-button" onClick={()=>{apply({type:'hint'});setHelp(true);}}><HelpCircle size={16}/> 一点提示</button><button className="primary" disabled={!canContinue(state)} onClick={next}>{chapter===6?'走向现实':chapter===5?'让线索相遇':'保存这段光'}<ArrowRight size={18}/></button></div>}
  </>}
  </section><div className="bottom-note"><button className="text-button" onClick={()=>apply({type:'visit',chapter:Math.max(0,chapter-1)})}><ArrowLeft size={13}/> 上一段</button><span>{saved?'可以随时离开，回来接着走。':'请保持页面打开，进度暂时无法保存。'}</span></div></main>
  <aside className="right-margin"><span>TRANSMISSION LOG</span><p>每一道微光<br/>都有来处。</p><span className="vertical-rule"/><small>{String(chapter).padStart(2,'0')} — 07</small></aside></div>}
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="story-dialog"><DialogTitle>让光再亮一点</DialogTitle><DialogDescription>{HINTS[chapter][Math.min(Math.max(0,hintCount-1),HINTS[chapter].length-1)]??'选择接收信号，开始这段旅程。'}</DialogDescription>{hintCount<HINTS[chapter].length&&<button className="secondary" onClick={()=>apply({type:'hint'})}>再给我一点提示</button>}<DialogClose className="text-button">继续寻找</DialogClose></DialogContent></Dialog>
  <Dialog open={journal} onOpenChange={setJournal}><DialogContent className="story-dialog journal"><DialogTitle>这一路收集的微光</DialogTitle><DialogDescription>每一个片段，都在慢慢靠近同一个答案。</DialogDescription><div className="journal-list">{state.wishes.length>0&&<p><span>随行的愿望</span>{state.wishes.map(n=>WORDS[n][0]).join(' · ')}</p>}{state.colorDone&&<p><span>光的颜色</span>{gift.favoriteColorName}{!gift.favoriteColorConfirmed?'（示例）':''}</p>}{state.stars===13&&<p><span>星空的痕迹</span>星点与星轨，短暂与停留</p>}{state.facets.length===3&&<p><span>属于你的石头</span>{gift.birthday} · {gift.birthstone}</p>}{state.decoded===3&&<p><span>回声的名字</span>W25 · .-- / ..--- / .....</p>}{state.assembled===4&&<p><span>相遇的形状</span>所有的线索，组成一条手链。</p>}</div><DialogClose className="secondary">带着它们继续 <ArrowRight size={17}/></DialogClose></DialogContent></Dialog>
  <Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent className="story-dialog"><DialogTitle>从第一束光开始？</DialogTitle><DialogDescription>这会清除这台设备上的游戏进度与愿望选择。</DialogDescription><button className="secondary" onClick={()=>{stopPlayback();apply({type:'reset'});setTune(18);setAngle(0);setResetOpen(false);}}>重新开始</button><DialogClose className="text-button">保留这段旅程</DialogClose></DialogContent></Dialog>
 </div>;
}

